### ISSUE TITLE
switch to the hubot-slack adapter

### ISSUE THREAD

**Issue by tenfourty** [tenfourty/chatbot#20]
https://github.com/slackhq/hubot-slack

currently using the irc adapter... but we've run out of integrations so we are stuck for now.

**Comment by carloseberhardt** [comment]
remove something? team time zone doesn't seem too critical? but i'm not using it, so that's not fair of me to say.. what's zapier doing, or it looks like we have three different calendar/meeting integrations set up today.. maybe one could go...

**Comment by tenfourty** [comment]
this is now fixed! formatting is much better and hubot in general works sweetly!
